feat: add frontend support for enabling automatic workspace updates
coder/coder pull request #10375
Opened 2023-10-21 22:21 UTC by sreya

This PR adds support for configuring an update policy for a workspace. Some behavior notes:

- A tooltip is displayed in the workspace stats bar if your update policy is overriden by the template-level setting.
- The ability to restart/start a workspace is hidden if an update is available for your workspace and your update policy evaluates to `always` even if the template-level setting is not enabled.

Workspace settings page: 

<img width="1425" alt="Screenshot 2023-10-21 at 5 15 29 PM" src="https://github.com/coder/coder/assets/4856196/e68fc3a9-4ff7-4757-87da-e8a32e17c4a4">

Workspace Page (Regular User) -- Policy=Never TemplatePolicy=Always:

<img width="1886" alt="Screenshot 2023-10-21 at 5 20 38 PM" src="https://github.com/coder/coder/assets/4856196/37d074b3-5473-4d1b-95d0-de95ba54d0d1">

2023-10-21 22:42 UTC, sreya commented
@aslilac the one issue I'm seeing is that after I submit the form in the workspace settings page the whole form stays disabled until I refresh the page 🤔

2023-10-30 16:22 UTC, aslilac commented on site/src/api/api.ts
> +  const data: TypesGen.UpdateWorkspaceAutomaticUpdatesRequest = {
nit: can we call this `req` or something. I think it just feels weird to declare `data` and return something called `data` in the same function.

2023-10-30 16:22 UTC, aslilac commented on site/src/components/Dashboard/DashboardProvider.tsx
> +};
why are we adding this function clear over here?

2023-10-30 16:22 UTC, aslilac commented on site/src/pages/WorkspaceSettingsPage/WorkspaceSettingsForm.tsx
> +  const autoUpdatesSet = ["never", "always"];
could we define these at the top level so that they stay static instead of getting allocated/gc'd for each rerender?

2023-10-30 16:22 UTC, aslilac commented on site/src/utils/workspace.tsx
> +  // Else prefer the workspace-level setting.
```suggestion

```

feels clear enough without the comment imo

2023-10-30 16:35 UTC, aslilac commented on site/src/components/Dashboard/DashboardProvider.tsx
> +};
oh I see, I guess this is fine

2023-10-30 16:44 UTC, aslilac commented on site/src/pages/WorkspaceSettingsPage/WorkspaceSettingsForm.tsx
> +          description="Configure your workspace to automatically update to the active template version when started."
```suggestion
          description="Configure your workspace to automatically update when started."
```

2023-10-30 16:54 UTC, aslilac commented on site/src/pages/WorkspaceSettingsPage/WorkspaceSettingsPage.tsx
> +      );
```suggestion
      await Promise.all([
        patchWorkspace(workspace.id, { name: formValues.name }),
        updateWorkspaceAutomaticUpdates(
          workspace.id,
          formValues.automatic_updates,
        ),
      ]);
```

2023-10-30 16:56 UTC, aslilac commented
I can't figure out how to reproduce the disabled form, but I'm happy to have a quick debugging session later

2023-10-30 16:59 UTC, aslilac commented on site/src/pages/WorkspaceSettingsPage/WorkspaceSettingsForm.tsx
>        name: nameValidator("Name"),
```suggestion
      name: nameValidator("Name"),
      automatic_updates: Yup.string().oneOf(autoUpdatesSet),
```

one last thing 😂

2023-10-31 15:47 UTC, aslilac approved these changes

2023-10-31 15:47 UTC, aslilac commented on site/src/pages/WorkspaceSettingsPage/WorkspaceSettingsForm.tsx
> +  AutomaticUpdateses,
this name sounds like we hired gollum 😂

2023-10-31 15:50 UTC, aslilac requested changes
oh, I just noticed that this broke one of the storybook tests. check chromatic, but after that's fixed it should be good to go.

2023-10-31 19:51 UTC, aslilac approved these changes

2023-10-31 22:06 UTC, merged