feat: add docker container example envbox template
coder/coder pull request #10802
Opened 2023-11-20 17:43 UTC by ericpaulsen

this PR adds an example template for running an `envbox` workspace as a Docker container. right now, our examples only include a Kubernetes-based template.

2023-11-20 17:45 UTC, sreya commented
Should we really be recommending this? If people are going to be running sysbox containers directly on a VM shouldn't we encourage them to run the daemon with the `sysbox-runc` runtime like we do for dogfood instead of adding an additional layer of abstraction?

The reason envbox exists for K8s is because it's a bit more difficult to manage sysbox on the nodes.

2023-11-20 17:58 UTC, ericpaulsen commented
@sreya I agree the daemon route should be the recommendation. though my thinking is, this template is helpful for quickly spinning up a Docker-enabled workspace, with no install necessary on the host. also, some customers are quite limited on what can be installed on the VM.

2023-11-22 07:40 UTC, matifali requested changes

2023-11-22 07:40 UTC, matifali commented on examples/templates/envbox-docker/main.tf
> +    "CODER_BOOTSTRAP_SCRIPT=${coder_agent.dev.init_script}",
I could not found this documented in README.md or https://github.com/coder/envbox

2023-11-22 07:40 UTC, matifali commented on examples/templates/envbox-docker/main.tf
> +    "CODER_MEMORY=2"
Should we move these to `coder_parameter` data sources?

2023-11-22 07:40 UTC, matifali commented on examples/templates/envbox-docker/main.tf
> +    "CODER_ADD_TUN=false",
Is it required? Doesn't it default to `false`?

2023-11-22 07:40 UTC, matifali commented on examples/templates/envbox-docker/main.tf
> +  }
Why do we need these mounts and volumes?

2023-11-22 07:40 UTC, matifali commented on examples/templates/envbox-k8s/README.md
> +`envbox` is an image that enables creating non-privileged containers capable of running system-level software (e.g. `dockerd`, `systemd`, etc) in Kubernetes.
```suggestion
[`envbox`](https://github.com/coder/envbox) is an image that enables creating non-privileged containers capable of running system-level software (e.g. `dockerd`, `systemd`, etc) in Kubernetes and Docker.
```

2023-11-22 07:40 UTC, matifali commented on examples/templates/envbox-k8s/README.md
> +
`CODER_BOOTSTRAP_SCRIPT` is missing from this list. Also, I think we should remove all ENVs not used in this example and instead refer to https://github.com/coder/envbox for complete documentation.

2023-11-22 07:40 UTC, matifali commented on examples/templates/envbox-k8s/README.md
> +```
We can remove this section as we no longer support the migration flow. Also, the migration docs have been removed.

2023-11-22 07:40 UTC, matifali commented on examples/templates/envbox-docker/README.md
All of the comments on envbox-k8s README apply here, too.

2023-12-03 00:11 UTC, closed without merging