fix: upsert replicas in cases where they could be deleted
coder/coder pull request #10895
Opened 2023-11-27 17:11 UTC by f0ssel

While I'm looking for things to work on I'm just tackling bugs

Closes https://github.com/coder/coder/issues/8858

2023-11-27 17:11 UTC, f0ssel commented
I have read the CLA Document and I hereby sign the CLA

2023-11-27 18:41 UTC, closed without merging

2023-11-28 04:41 UTC, spikecurtis requested changes
I'd also like to see a unit test that reproduces #8858 and shows that this fixes it.

2023-11-28 04:41 UTC, spikecurtis commented on coderd/database/queries/replicas.sql
> +    hostname,
I think we should include `stopped_at` on the `INSERT` as well.  We'd expect it not to be set when a replica inserts itself the first time, but having an asymmetry between `INSERT` and `UPDATE` on an "upsert" can lead to confusing results.

For example, if one Coderd deletes a row, then another upserts it with `stopped_at` set to `now()`, we'd reinsert it without the `stopped_at`.

2023-11-28 04:41 UTC, spikecurtis commented on coderd/database/dbmem/dbmem.go
> +func (q *FakeQuerier) UpsertReplica(_ context.Context, arg database.UpsertReplicaParams) (database.Replica, error) {
This implementation needs to be changed to insert if not present!

2023-11-28 04:41 UTC, spikecurtis commented on coderd/database/models.go
> +//   sqlc v1.24.0
You'll need to get your environment matching CI --- easiest is to use the Coder on Coder template, or Nix.