chore: add workspace cleanup docs
coder/coder pull request #11146
Opened 2023-12-12 01:06 UTC by sreya

2023-12-22 05:13 UTC, matifali commented
@bpmct @stirby we should get this in.

2024-01-05 11:14 UTC, matifali approved these changes

2024-01-05 11:21 UTC, matifali requested changes
It needs to be updated to remove all reference to the feature being experimental as we are moving it out of experimental in #11427

2024-01-16 18:07 UTC, matifali approved these changes

2024-01-16 20:49 UTC, matifali approved these changes

2024-01-16 20:49 UTC, matifali commented on docs/images/template-scheduling.png
@stirby could you update screenshot as it's no more alpha.

2024-01-16 21:12 UTC, merged

2024-01-16 21:18 UTC, matifali commented on docs/images/template-scheduling.png
@sreya we needed to update the screenshot to remove Alpha labels.

2024-01-16 21:22 UTC, sreya commented on docs/images/template-scheduling.png
We'd need to remove the tags in the product first since they're still there.