chore: add additional fields to license telemetry
coder/coder pull request #11173
Opened 2023-12-13 00:18 UTC by coadler

2023-12-13 00:18 UTC, coadler commented
Current dependencies on/for this PR:
* `main`
  * **PR #11173** <a href="https://app.graphite.dev/github/pr/coder/coder/11173?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/11173?utm_source=stack-comment).

2023-12-13 21:05 UTC, ammario requested changes

2023-12-13 21:05 UTC, ammario commented on coderd/coderd.go
> +	ParseLicenseClaims func(rawJWT string) (email string, trial bool, err error)
The jankiness demands an in-line comment

2023-12-14 00:41 UTC, ammario approved these changes

2023-12-14 21:52 UTC, merged