fix: ensure wsproxy `MultiAgent` is closed when websocket dies
coder/coder pull request #11414
Opened 2024-01-04 18:51 UTC by coadler

The `SingleTailnet` behavior only checked to see if the `MultiAgent` was
closed, but the websocket error was not being propogated into the
`MultiAgent`, causing it to never be swapped for a new working one.

2024-01-04 18:51 UTC, coadler commented
Current dependencies on/for this PR:
* `main`
  * **PR #11414** <a href="https://app.graphite.dev/github/pr/coder/coder/11414?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/11414?utm_source=stack-comment).

2024-01-05 04:02 UTC, spikecurtis requested changes
Good work tracking down the bug!

I don't see any new tests though that will catch and prevent a regression, so please add

2024-01-05 04:02 UTC, spikecurtis commented on enterprise/wsproxy/wsproxysdk/wsproxysdk.go
> +		<-ctx.Done()
If I'm understanding this correctly, we're depending on the fact that the reader goroutine below cancels the context on a failed read.

I think we should _also_ tear down the multi-agent on a failed write of subscription messages. It's unlikely that we'd have a failure that leaves the connection half-open (e.g. for reads but not writes), but such things are possible and you don't want the proxy limping on unable to subscribe to new agents.

2024-01-05 04:02 UTC, spikecurtis commented on coderd/httpapi/websocket.go
>  	for {
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 43 to 43]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->Drop an INFO log here<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/coder/coder/11414?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-01-11 16:31 UTC, spikecurtis approved these changes

2024-01-11 17:37 UTC, merged