docs: update modules docs
coder/coder pull request #11911
Opened 2024-01-30 10:04 UTC by matifali

I refactored module docs to remove duplication and hope to achieve a better flow.

Also fixed some old links

2024-01-30 18:44 UTC, stirby commented on docs/templates/modules.md
> +#### Passing git credentials in Kubernetes
I think that's great, want to build a culture where guides contain most of our tutorials and the docs become pure technical reference. 

+1 from me.

2024-01-30 20:07 UTC, matifali commented on docs/templates/modules.md
> +#### Passing git credentials in Kubernetes
@ericpaulsen could you help in moving this to guides? 
I want to keep it general so that we can refer it at many places.

2024-01-30 20:07 UTC, matifali commented on docs/templates/modules.md
> +#### Passing git credentials in Kubernetes
We can do that in a separate PR too or feel free to push to this PR.

2024-02-05 07:37 UTC, matifali commented on docs/templates/modules.md
> +#### Passing git credentials in Kubernetes
Not doing it in this pr

2024-02-13 15:28 UTC, bpmct approved these changes

2024-02-13 15:28 UTC, bpmct requested changes

2024-02-13 15:28 UTC, bpmct commented on docs/templates/modules.md
> +> Do not forget to replace example.jgrog.io with uour Artifactory URL
typos!

2024-02-13 15:28 UTC, bpmct approved these changes

2024-02-13 15:31 UTC, matifali commented on docs/templates/modules.md
> +> Do not forget to replace example.jgrog.io with uour Artifactory URL
fixed

2024-02-13 15:35 UTC, merged