docs: simplify install docs
coder/coder pull request #11946
Opened 2024-01-30 22:20 UTC by bpmct

While we support a diverse amount of installation methods, only power users will want to use a system service/non-install script. Folks who want to run a system service on a full-time VM should understand how to start it and keep it running. We can always make a guide/tutorial for this that walks through the basics

| Before | After |
| -- | -- |
| <img width="506" alt="Screenshot 2024-01-30 at 4 18 30 PM" src="https://github.com/coder/coder/assets/22407953/12353809-534c-4c80-b6e7-6eda97fa244b">| ![image](https://github.com/coder/coder/assets/22407953/6d59595f-e859-4c53-8644-b784febe27f3) |

2024-01-30 22:37 UTC, matifali reviewed
I am ok with this refactoring but we are now burying all the installation m this we support. We should have them somewhere got the people who need. 

Probably the full original detailed installation methods could be moved to a tutorial or guide in the guides section. 
I don't think we should just delete it.

2024-01-30 22:37 UTC, matifali commented on docs/install/index.md
> +Use [GitHub releases](https://github.com/coder/coder/releases) to download the Windows installer (`.msi`) or standalone binary (`.exe`).
Why preferring installer over Winget while Winget is built-in to Windows and also supports arm64 out of the box?

2024-01-30 22:39 UTC, matifali commented
Could you copy the existing install sh as is to a new guide with a title "How to install Coder?"

2024-01-30 22:41 UTC, matifali requested changes
I am ok with this refactoring but we are now burying all the installation m this we support. We should have them somewhere got the people who need. 

Probably the full original detailed installation methods could be moved to a tutorial or guide in the guides section. 
I don't think we should just delete it. 

Could you copy the existing install sh as is to a new guide with a title "How to install Coder?"

2024-01-31 13:11 UTC, matifali requested changes

2024-01-31 13:11 UTC, matifali commented on docs/install/index.md
> +- [Create your first template](./1-click.md)
```suggestion
- [Create your first template](../templates/index.md)
```

2024-01-31 13:11 UTC, matifali commented on docs/install/index.md
> +Refer to [GitHub releases](https://github.com/coder/coder/releases) for alternate installation methods (e.g. standalone binaries, system packages).
```suggestion
Alternatively, you can use the [Homebrew](https://brew.sh/) package
manager to install Coder.

	```shell
	brew install coder/coder/coder
	```

Refer to [GitHub releases](https://github.com/coder/coder/releases) for alternate installation methods (e.g. standalone binaries, system packages).
```

Do we want to mention our Homebrew packages anywhere?

2024-01-31 13:18 UTC, matifali approved these changes
I revisited and agree with the refactoring. A few suggestions regarding wrong/old links and it's good to merge.

2024-02-05 07:29 UTC, matifali commented
@bpmct, do you want to make any further changes before merging?

2024-02-06 12:07 UTC, bpmct commented
Yeah, I have several changes planned! Should have the rest pushed soon

2024-02-18 06:00 UTC, matifali commented
@bpmct I think you still want to complete this.

2024-03-08 15:15 UTC, merged