feat: add filter by status on GET /users
coder/coder pull request #1206
Opened 2022-04-28 13:19 UTC by BrunoQuaresma

Discussion: https://github.com/coder/coder/issues/662#issuecomment-1110005587

Reason: The FE needs to get only the active users for now, so I think the best way for doing that is to add a filter on the GET /users endpoint so the FE can do /users?status=active.

2022-04-28 13:31 UTC, Emyrk requested changes

2022-04-28 15:11 UTC, presleyp approved these changes
Yeah that approach works for me!

2022-04-28 19:41 UTC, Emyrk requested changes
1 last comment

2022-04-29 13:29 UTC, Emyrk approved these changes

2022-04-29 13:29 UTC, merged