chore: shutdown provisioner should stop waiting on client
coder/coder pull request #13118
Opened 2024-05-01 18:06 UTC by Emyrk

I do not think this is quite correct. 

Run `go run main.go provisionerd start` without a coderd. After a second or two, hit `ctrl +c`. The process will not terminate. The issue is we call `Shutdown` for a graceful closure.

Currently:
- `connect()` does not terminate on shutdown. [Only on `Close`](https://github.com/coder/coder/blob/4142fb3576ef2899efdd8a5eba024be95556779a/provisionerd/provisionerd.go#L195-L197)
- `Shutdown` does not call close. The caller needs to call [`Shutdown` and then `Close`](https://github.com/coder/coder/blob/4142fb3576ef2899efdd8a5eba024be95556779a/provisionerd/provisionerd_test.go#L674-L677). Updated the cli to do this, although it is not intuitive imo.
- `acquireLoop` blocks on a client, but if no client is ever established, the shutdown never gets checked, and this blocks forever.

This PR calls `Close` after `Shutdown` and makes `p.client()` return a nil client during shutdown.

2024-05-02 07:44 UTC, spikecurtis requested changes
Can we get a unit test?

2024-05-02 14:30 UTC, Emyrk commented
@spikecurtis test added: https://github.com/coder/coder/blob/418c4ddfc8c458c923a5d0495adb54aa5ea1b090/provisionerd/provisionerd_test.go#L602-L630

2024-05-03 05:16 UTC, spikecurtis approved these changes
LGTM!

2024-05-03 05:16 UTC, spikecurtis commented on provisionerd/provisionerd_test.go
> +		require.Condition(t, closedWithin(connectAttempted, testutil.WaitShort))
just FYI, we have `testutil.RequireRecvCtx()` which is what I usually use for this sort of thing.

2024-05-03 15:15 UTC, merged