ci: add networking release validation
coder/coder pull request #14273
Opened 2024-08-15 07:43 UTC by ethanndickson

2024-08-15 07:43 UTC, ethanndickson commented
* **#14273** <a href="https://app.graphite.dev/github/pr/coder/coder/14273?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ethanndickson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-15 07:48 UTC, ethanndickson commented on .github/workflows/release-validation.yaml
> +    runs-on: ${{ github.repository_owner == 'coder' && 'depot-ubuntu-22.04-8' || 'ubuntu-latest' }}
This is to please the CI linter.

2024-08-15 08:30 UTC, matifali requested changes

2024-08-15 08:30 UTC, matifali commented on .github/workflows/release-validation.yaml
> +    runs-on: ${{ github.repository_owner == 'coder' && 'depot-ubuntu-22.04-8' || 'ubuntu-latest' }}
```suggestion
    runs-on: ubuntu-latest
```
As this action only triggers a repository dispatch event, it should not need an 8-core runner and would do well on the free `ubuntu-latest` runner.

I am assuming standard GitHub action linux runners are free to use on public repos i.e., `ubuntu-latest`
This [page](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) says:
> The use of these runners on public repositories is free and unlimited.

2024-08-16 16:16 UTC, deansheather approved these changes

2024-08-16 16:16 UTC, deansheather commented on .github/workflows/release-validation.yaml
> +    branches: 08-15-ci_add_networking_release_validation
remember to remove

2024-08-19 06:27 UTC, ethanndickson commented
Merging blocked by the requested changes.

2024-08-19 06:31 UTC, matifali approved these changes

2024-08-19 06:31 UTC, merged