chore(docs): update external provisioners helm docs
coder/coder pull request #15155
Opened 2024-10-21 09:26 UTC by johnstcn

Closes https://github.com/coder/coder/issues/14985

Updates external provisioner documentation to show steps for using provisioner keys via Helm:

2024-10-21 09:57 UTC, spikecurtis approved these changes

2024-10-22 18:02 UTC, EdwardAngert requested changes

2024-10-22 18:02 UTC, EdwardAngert commented on docs/admin/provisioners.md
> +   # Optionally, you can specify tags for the provsioner key:
```suggestion
   # Optionally, you can specify tags for the provisioner key:
```

2024-10-22 18:02 UTC, EdwardAngert commented on docs/admin/provisioners.md
> +   Store the key in a kubernetes secret:
```suggestion
1. Store the key in a kubernetes secret:
```

2024-10-22 19:36 UTC, EdwardAngert approved these changes

2024-10-23 08:25 UTC, merged