chore(docs): clarify that variables be edited through the web UI
coder/coder pull request #15799
Opened 2024-12-09 15:38 UTC by phorcys420

When visiting a community user 2 weeks ago, they pointed out that we don't clearly state that template-wise variables can be edited through the web UI.

This PR adds a line to (hopefully) clarify this.
I didn't find other places where this could be added, but feel free to let me know!

2024-12-09 16:13 UTC, EdwardAngert requested changes

2024-12-09 16:13 UTC, EdwardAngert commented on docs/admin/templates/extending-templates/variables.md
> +2. _Web UI_: You can set and/or edit variable values under "Variables" in the template's settings.
```suggestion
1. _Web UI_: You can set or edit variable values under **Variables** in the template's settings.   
```

2024-12-09 16:13 UTC, EdwardAngert commented on docs/admin/templates/extending-templates/variables.md
> +3. _Command-line argument_: Utilize the `--var name=value` command-line argument
```suggestion
1. _Command-line argument_: Utilize the `--var name=value` command-line argument
```

2024-12-09 16:13 UTC, EdwardAngert commented on docs/admin/templates/extending-templates/variables.md
> +4. _Variables file selection_: Alternatively, you can use a variables file
```suggestion
1. _Variables file selection_: Alternatively, you can use a variables file
```

2024-12-09 21:37 UTC, phorcys420 commented
@EdwardAngert out of curiosity, why make everything `1.`?

2024-12-09 22:14 UTC, EdwardAngert commented
> @EdwardAngert out of curiosity, why make everything `1.`?

@phorcys420 it's mostly preference - markdown doesn't really care what numbers you use as long as the spacing is correct. I default to using the [Google developer style guide](https://developers.google.com/style/) and the GitLab docs style guide](https://docs.gitlab.com/ee/development/documentation/styleguide/). My personal preference is to use `1.` so that in cases like this, when we add or remove a number, it's all already `1.` so you don't have to adjust other steps to match.

- [GitLab docs style guide](https://docs.gitlab.com/ee/development/documentation/styleguide/#choose-between-an-ordered-or-unordered-list)
- [MD029](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md029---ordered-list-item-prefix)

2024-12-09 22:15 UTC, EdwardAngert approved these changes

2024-12-18 15:43 UTC, EdwardAngert commented
pushing a commit to see if I can fix those errors and get this merged

2024-12-18 15:55 UTC, merged