feat: expose max timeout to schedule form
coder/coder pull request #3497
Opened 2022-08-12 20:13 UTC by oxy

This PR exposes the maximum timeout to the validator in the schedule form.

## Subtasks

- [x] update state machine to load template
- [x] expose max TTL to form
- [x] generate validators with custom TTL

Fixes #2752

2022-08-15 16:27 UTC, kylecarbs approved these changes

2022-08-15 20:03 UTC, Kira-Pilot requested changes
I'm seeing a brief error state on page load and refresh. Do you mind taking a look? I don't see it on main.
![Kapture 2022-08-15 at 16 02 24](https://user-images.githubusercontent.com/19142439/184709029-9a4ef52a-bff4-46b9-bbad-ff10cd8ae858.gif)

2022-08-15 20:08 UTC, Kira-Pilot commented
Can we add tests to `WorkspaceScheduleForm.test.ts` to cover the following cases:
1. user can set TTL below template max
2. user can't set TTL above template max

There is a `MockTemplate` entity you can use in `site/src/testHelpers/entities.ts`. LMK if you need any help!

2022-08-16 16:04 UTC, presleyp commented
@misskniss and I decided to close this in favor of higher priority items for now; it can be re-opened later!

2022-08-16 16:04 UTC, closed without merging