feat(setup): organization is not longer needed
coder/coder pull request #4707
Opened 2022-10-23 16:11 UTC by ghuntley

nb; I have not tested these changes // they were doing up on a airplane 🙃

Resolves (in theory) https://github.com/coder/coder/issues/4697

2022-10-24 14:41 UTC, Kira-Pilot requested changes
Thanks for taking a look at this one! It seems to me that[ the API is asking](https://github.com/coder/coder/blob/main/site/src/api/typesGenerated.ts#L143) we send down an organization. You can see where we send down data of this type [in `api.ts`](https://github.com/coder/coder/blob/main/site/src/api/api.ts#L452).

Not sure what needs to be altered server-side here, but we'll need to regenerate those types after a change is made so that lint stops complaining.

2022-11-14 02:01 UTC, ghuntley commented
I went back in there and removed all backend references. Would appreciate a second set of eyes on this one as first time making backend+frontend changes in the project.

2022-11-14 18:25 UTC, Kira-Pilot commented on site/src/pages/SetupPage/SetupPageView.tsx
> -            fullWidth
It might be nice to give `autoFocus` to the next field so that users can start typing without clicking into the form.

2022-11-14 18:25 UTC, Kira-Pilot approved these changes
FE ✅

2022-11-18 05:55 UTC, closed without merging