docs: update port forwarding to state it works without a wildcard with tunnel
coder/coder pull request #4887
Opened 2022-11-03 23:40 UTC by sharkymark

This PR:

1. Clarifies the port forwarding dashboard docs to state that port forwarding works without a wildcard domain environment variable when tunnel (reverse proxy) is used.

2022-11-03 23:51 UTC, ammario requested changes, later dismissed

2022-11-03 23:51 UTC, ammario commented on docs/networking/port-forwarding.md
> +> URL length is greater than 63 characters, port fordwarding will not work.
```suggestion
> URL length is greater than 63 characters, port forwarding will not work.
```

2022-11-04 20:01 UTC, bpmct approved these changes

2022-11-09 09:01 UTC, ghuntley commented on docs/networking/port-forwarding.md
> +> [wildcard access URL](../admin/configure.md#wildcard-access-url). If an access
```suggestion
> [wildcard access URL](../admin/configure#wildcard-access-url). If an access
```

2022-11-09 10:25 UTC, merged