chore: Skip reconnect and complete test
coder/coder pull request #5160
Opened 2022-11-23 20:51 UTC by BrunoQuaresma

The test is failing quite frequently so I'm skipping it until we have it fixed. Issue: https://github.com/coder/coder/issues/5159

2022-11-23 20:53 UTC, coadler requested changes

2022-11-23 20:53 UTC, coadler commented on provisionerd/provisionerd_test.go
> +	t.Skip("ReconnectAndComplete", func(t *testing.T) {
```suggestion
	t.Run("ReconnectAndComplete", func(t *testing.T) {
	t.Skip("Test is flakey. See: https://github.com/coder/coder/issues/5159")
```

2022-11-24 03:14 UTC, coadler approved these changes

2022-11-24 12:15 UTC, mafredri commented
I just merged #5159, should (hopefully) fix the flakeyness of this test (and we can leave it enabled).

2022-11-24 13:09 UTC, closed without merging