Sort template versions by descending creation date
coder/coder pull request #5163
Opened 2022-11-23 22:21 UTC by goodspark

The most recent is likely the most relevant for people using this command.

2022-11-26 18:32 UTC, goodspark commented
I have read the CLA Document and I hereby sign the CLA

2022-12-01 21:46 UTC, kylecarbs approved these changes

2022-12-09 11:39 UTC, mafredri requested changes

2022-12-09 11:39 UTC, mafredri commented on cli/templates.go
> +	sort.SliceStable(rows, func(i, j int) bool { return rows[i].CreatedAt > rows[j].CreatedAt })
This should be after the for-loop.

2023-01-02 00:11 UTC, closed without merging