feat: Add datadog tracing to http middleware
coder/coder pull request #530
Opened 2022-03-22 21:16 UTC by f0ssel

2022-03-22 21:23 UTC, kylecarbs approved these changes
Two minor things, but LGTM!

2022-03-22 21:32 UTC, deansheather approved these changes

2022-03-25 16:26 UTC, kylecarbs approved these changes
Let's add a thin-test to call start and stop with goleak. Then we can ensure no goroutines are leaked!

Apart from my one structural comment, this is awesome! Thoughts on adding a CLI flag to enable/disable tracing with the `DATADOG_TOKEN`? I'd rather this not be implicit, just in case customers want to disable it.

We can add that to `coder.env` too. That's used by our systems service in our dogfood deployment! Tracing in dogfood😎

2022-03-28 20:07 UTC, kylecarbs requested changes

2022-03-28 21:50 UTC, kylecarbs approved these changes

2022-03-28 22:11 UTC, merged