feat: refactor deployment config
coder/coder pull request #6347
Opened 2023-02-25 23:59 UTC by ammario

This PR introduces a new `bigcli` package and refactors `coder server` to use it instead of cobra/viper. It enables non-janky long-help formatting, doc generation, and YAML support.

Overall it should reduce lines of code, complexity, and dramatically improve the user experience for the deployer.

2023-03-01 01:07 UTC, kylecarbs requested changes

2023-03-01 01:07 UTC, kylecarbs commented on coderd/deploymentconfig.go
> +		codersdk.DeploymentConfigAndOptions{
Seems like these are more like values and usage. Config and options sound too similar, it's difficult to differentiate. Not sure on the naming I suggested, just an option.

2023-03-01 01:07 UTC, kylecarbs commented on codersdk/deployment.go
> +func (c *DeploymentConfig) Scrub() (*DeploymentConfig, error) {
I like the name `Scrub`, but I might name this `WithoutSecrets` instead... it's more verbose but less strenuous to the reader to understand.

2023-03-01 01:07 UTC, kylecarbs commented on enterprise/coderd/appearance_test.go
> +	cfg.Support.Links = bigcli.Object[[]codersdk.LinkConfig]{
I might call this `bigcli.Struct` instead of `Object`. `Object` sounds very Java or JavaScript-esque.

2023-03-01 01:07 UTC, kylecarbs commented on site/src/util/deployOptions.ts
> +  const found: DeploymentOption[] = []
Wrap this in a `useMemo` hook to prevent searching from hundreds of options on re-render!

2023-03-06 11:11 UTC, mafredri reviewed
I haven't taken a look at the actual CLI output, but so far this seems like an improvement over what we have. I'd like to see the re-introduction of golden files (for the server command) so that visual changes are always verified.

It looks like a few things are still missing for this to be mergeable, so just leaving comments for now.

PS. I'm not sold on the name, what makes it `big`? 😆.

2023-03-06 18:14 UTC, ammario commented
> PS. I'm not sold on the name, what makes it `big`? 😆.

Struggled to find a good name, but `big` because it's meant to support bigger CLIs lol. If we think it's not very clear, I'm also down to use a more "cute" name like `serpent` (following on the cobra/viper snake theme).

2023-03-06 18:24 UTC, ammario commented on cli/bigcli/command.go
> +func (c *Command) FullUsage() string {
We do so in the help template, perhaps not validly.

2023-03-06 18:45 UTC, ammario commented on cli/bigcli/option.go
> +func (s OptionSet) SetDefaults() error {
The main reason is I haven't built out the `Command` type, which would contain the logic and happens in a follow-up PR.

2023-03-06 18:47 UTC, ammario commented on cli/bigcli/values.go
> +	return fmt.Sprintf("struct[%T]", s.Value)
Renamed the type, so now there is.

2023-03-06 18:51 UTC, ammario commented on cli/bigcli/yaml.go
> +	for i := 0; i < len(n.Content); i += 2 {
Good catch.

2023-03-06 18:56 UTC, ammario commented on cli/bigcli/yaml.go
> +			group = append(group, strings.ToLower(g.Name))
Honestly going to stabilize the YAML in a follow-up PR. I made the YAML flags hidden for now.

2023-03-06 18:56 UTC, ammario commented on cli/bigcli/yaml_test.go
> +		t.Logf("Raw YAML:\n%s", string(byt))
Yep, I'm going to do this in a follow-up since this PR is already massive.

2023-03-06 18:57 UTC, ammario commented on cli/clitest/clitest.go
> +	)
perhaps, changed

2023-03-06 19:04 UTC, ammario commented on cli/config/file.go
> +func (r Root) DeploymentValuesPath() string {
This function should be killed actually.,

2023-03-06 19:05 UTC, ammario commented on cli/usage.go
> +					return groups[i].Name < groups[j].Name
No, we're not sure, but only the server command has groups right now, and we should feel free to change the structure of help output whenever we want.

2023-03-06 19:05 UTC, ammario commented on cli/usage.tpl
> +{{ indent $desc 2}}
It looks good in the CLI, so I don't think it matters either way.

2023-03-06 19:06 UTC, ammario commented on codersdk/deployment.go
> +func (c *DeploymentValues) Scrub() (*DeploymentValues, error) {
It's a good idea but this is no more insecure than the prior implementation, so don't want to improve it right now.

2023-03-07 20:18 UTC, kylecarbs approved these changes
Some manual stuff testing:

![image](https://user-images.githubusercontent.com/7122116/223541948-36477244-aa21-4ddf-b4eb-95826d6a701c.png)
^See the lack of space between `running` and `Coder`

![image](https://user-images.githubusercontent.com/7122116/223542257-0586c391-49e8-4247-a47b-b2cb1f3429bd.png)
^It says "Git Authentication Providers" randomly

![image](https://user-images.githubusercontent.com/7122116/223542377-edd287d0-8a3a-460f-8055-a7528bd0de42.png)
^It's worth manually checking if this is still working by default. I know the value was false before, but somehow internally I think it was actually true.

![image](https://user-images.githubusercontent.com/7122116/223542639-3eff35ed-2be4-4502-88cc-90757f01f707.png)
This is in the deployment settings.

2023-03-07 20:18 UTC, kylecarbs commented on cli/root_test.go
> +		// TODO: re-enable after bigcli migration.
clibase

2023-03-07 20:18 UTC, kylecarbs commented on cli/clibase/bigcli.go
> +// Package clibase offers an all-in-one solution for a highly configurable CLI
This file should be called `clibase.go`

2023-03-07 20:18 UTC, kylecarbs commented on cli/clibase/env.go
> +package clibase
The naming of `environment` is abbreviated to `env` but `command` not to `cmd` bothers me. Let's make this consistent.

2023-03-07 21:10 UTC, merged