chore: reorganize some docs
coder/coder pull request #7062
Opened 2023-04-10 13:47 UTC by bpmct

2023-04-10 13:54 UTC, kylecarbs approved these changes

2023-04-12 14:08 UTC, matifali approved these changes
You may want to run https://github.com/coder/coder/actions/workflows/cron-weekly.yaml after merging this.

2023-04-12 14:08 UTC, matifali commented on docs/admin/configure.md
> +Coder server's primary configuration is done via environment variables. For a full list of the options, run `coder server --help` on the see our [CLI documentation](../cli/server.md).
```suggestion
Coder server's primary configuration is done via environment variables. For a full list of the options, run `coder server --help` or see our [CLI documentation](../cli/server.md).
```

2023-04-12 14:08 UTC, matifali commented on docs/admin/configure.md
> +Coder server's primary configuration is done via environment variables. For a full list of the options, run `coder server --help` on the see our [CLI documentation](../cli/server.md).
a minor typo I think.

2023-04-12 14:09 UTC, matifali requested changes
A minor typo I think.

2023-04-12 21:47 UTC, merged