chore: skip ts or go tests based on files changed
coder/coder pull request #7134
Opened 2023-04-14 13:33 UTC by deansheather

2023-04-14 13:35 UTC, BrunoQuaresma approved these changes
Thank you!

2023-04-14 13:40 UTC, mafredri commented on .github/workflows/ci.yaml
> +              - "site/static/error.html"
Would it make sense to do negative match instead?

E.g.

```yaml
- "**"
- "!site"
- ...
```

2023-04-14 14:08 UTC, matifali requested changes

2023-04-14 14:08 UTC, matifali commented on .github/workflows/ci.yaml
> +              - "docs/**"
you should add `./README.md` heer too
```suggestion
              - "docs/**"
              - "./README.md"
```

2023-04-14 19:08 UTC, coadler approved these changes

2023-04-14 19:08 UTC, coadler commented on .github/workflows/ci.yaml
> +      sh: ${{ steps.filter.outputs.sh }}
`sh` doesn't seem to be used anywhere

2023-04-17 12:07 UTC, mafredri commented on .github/workflows/ci.yaml
> +              - "site/static/error.html"
For those I think it should work to do the following:

```yaml
- "**"
- "!site"
- "site/*.go"
```

2023-04-17 16:10 UTC, deansheather commented on .github/workflows/ci.yaml
> +              - "site/static/error.html"
I'm kinda dubious whether that would work or not. There's no example in the readme of this action like that

2023-04-17 16:18 UTC, deansheather commented on .github/workflows/ci.yaml
> +              - "site/static/error.html"
This doesn't seem to work in picomatch from my testing

2023-04-26 13:20 UTC, matifali approved these changes

2023-05-04 00:52 UTC, matifali commented
unstale. @deansheather

2023-06-09 17:27 UTC, ammario requested changes
I tried this once before, but it caused issues because the required status checks would never pass on e.g. a docs PR.

We could get around that by checking the changed files in the `run` body, and `exit 0` early if no relevant files changed.

In an ideal world, test caching would make all of this a non-issue.

2023-06-09 17:40 UTC, matifali commented
I discussed this with @deansheather and he said that he will change the settings to make the new required job as required. So it will work in that case.

2023-06-09 18:06 UTC, ammario approved these changes
Clever clever dean

2023-06-09 18:36 UTC, matifali commented
I will wait for @deansheather to take a final look and then merge.

2023-06-09 23:53 UTC, merged