feat: Add strict transport security and secure cookie options
coder/coder pull request #741
Opened 2022-03-30 19:47 UTC by f0ssel

2022-03-30 20:11 UTC, Emyrk submitted a review, later dismissed

2022-03-30 21:19 UTC, kylecarbs requested changes

2022-03-30 22:47 UTC, kylecarbs approved these changes
Make sure to rename the `hsts*.go` files before merge. I added another comment about renaming `secureCookie` to `secureAuthCookie` instead, which I think makes it a bit more explicit.

I don't think we should export objects _just_ for testing. Apart from that, looks good to me!

2022-03-31 14:23 UTC, kylecarbs requested changes

2022-03-31 14:43 UTC, kylecarbs requested changes

2022-03-31 15:43 UTC, kylecarbs approved these changes
LGTM! One comment is just a question, not a change.

2022-03-31 17:01 UTC, ammario submitted a review, later dismissed
(See my comment)

2022-03-31 17:31 UTC, merged