test: Add unit test for rbac `Authorize()` function
coder/coder pull request #853
Opened 2022-04-04 14:47 UTC by Emyrk

# What this does

The main objective of this PR is to write the unit test for the `Authorize()` function before it is implemented. As consequence the function is also stubbed for use before authz is ready.

# Unit test coverage

The only lines not covered will be covered or removed with the Authz implementation. The lines exist as stubs for "using" the library before it is ready. 100% will be reached as the implementation is introduced 

# Issues

Implement tests for permissions: https://github.com/coder/coder/issues/715
Implement stub function to authenticate: https://github.com/coder/coder/issues/718
Build the struct for permission format for RBAC: https://github.com/coder/coder/issues/720

2022-04-04 15:09 UTC, kylecarbs reviewed
Did we decide against using OPA?

2022-04-04 15:50 UTC, kylecarbs reviewed
Could an example be added? I'm a bit confused how this package would be consumed.

2022-04-05 13:32 UTC, johnstcn approved these changes

2022-04-05 15:08 UTC, kylecarbs reviewed
Mostly questions here. Steven and I hopped in Discord which helped me understand the objective quite a bit.

Minor nit: in other places we haven't used `_` in test names. I'm impartial to either way, but we should be consistent.

2022-04-06 14:05 UTC, kylecarbs requested changes

2022-04-06 14:07 UTC, kylecarbs requested changes

2022-04-08 15:11 UTC, closed without merging