feat: Add update profile endpoint
coder/coder pull request #916
Opened 2022-04-07 20:04 UTC by BrunoQuaresma

Related to #975

2022-04-07 23:51 UTC, kylecarbs requested changes

2022-04-08 15:07 UTC, Emyrk reviewed
Left 1 comment on the name field. We should use the existing name field if the new name field is `""` or `nil`

2022-04-10 15:55 UTC, kylecarbs requested changes

2022-04-12 13:50 UTC, kylecarbs approved these changes
Looks good to me!

2022-04-12 14:05 UTC, merged