feat: Add RBAC package for managing user permissions
coder/coder pull request #929
Opened 2022-04-08 17:18 UTC by Emyrk

# What this does

[`Authorize`][authorize] is the stub function that will be called externally. This is the main entry-point for the package.

#715 , #716, #718, #720,  #725

## Making a user with given roles

See [example_test.go][example_roles] to see how to add multiple roles to a user. `SubjectTODO` is a placeholder, and roles can be serialized for db storage. Serialization is not implemented until required.

```golang
user := authz.SubjectTODO{
	UserID: "alice",
	Roles: []authz.Role{
		authz.RoleOrgAdmin("default"),
		authz.RoleSiteMember,
	},
}
```

## Using `Authorize`

`Authorize` is a function on an `authorizer`. For now, the authorizer just precompiles a builtin rego policy. 

For example, to "Read all workspaces in the org `Coder`", we create a `ResourceWorkspace` owned by the org `Coder`

```golang
// In practice 'Coder' would be a uuid
authz.Authorize(ctx, user.ID, user.Roles, authz.ActionRead, authz.ResourceWorkspace.InOrg("Coder"))
```

To read all workspaces across the whole product, we omit the owner id since we want to include the set of all workspaces.

```golang
authz.Authorize(ctx, user.ID, user.Roles,  authz.ActionRead, authz.ResourceWorkspace.All())
```

# Making a new Role

Most roles are just `*` and easy to write. One example of enumerating certain permissions uses a helper function to keep the role as few LoC: https://github.com/coder/coder/blob/f5d95efd25f49720f198fd366e3c51911ce13459/coderd/authz/role.go#L40-L47

The helper func omits negative permissions, but those can be defined [explicitly](https://github.com/coder/coder/blob/f5d95efd25f49720f198fd366e3c51911ce13459/coderd/authz/role.go#L51-L62). Note that no builtin roles require negative permissions, and are only needed for edge cases that we don't need to support in MVP.

# Benchmarks

736 permission checks were done in <300ms. I think this is fast enough. 
The rego handles role expansion, which is kinda neat.

[authorize]: https://github.com/coder/coder/blob/44a7679ed8edb3579188f9c5c9f3b3d28552ea49/coderd/rbac/authz.go#L41
[example_roles]: https://github.com/coder/coder/blob/c7dc715772b1db7f7fa6ea03fb34e8512d9e6ee1/coderd/authz/example_test.go#L19-L25

2022-04-08 18:13 UTC, kylecarbs requested changes

2022-04-11 17:12 UTC, kylecarbs reviewed
More discussion and less nits on the code. Getting pretty close 🥳🥳🥳

2022-04-12 14:59 UTC, kylecarbs approved these changes
I think we should change the PR title to something like: `feat: Add RBAC package for managing user permissions`. This is a big deal!

2022-04-13 13:27 UTC, johnstcn approved these changes

2022-04-13 13:35 UTC, merged