docs: add jetbrains offline mode config steps
coder/coder pull request #9388
Opened 2023-08-28 16:17 UTC by ericpaulsen

this PR adds steps we took to build out a POC of the [JetBrains Offline Mode](https://www.jetbrains.com/help/idea/fully-offline-mode.html).

customers have struggled configuring this solution, so this is intended to help. note that this POC has only been tested with the manual SSH configuration in Gateway (and did not use the Coder plugin).

2023-08-28 16:50 UTC, ericpaulsen commented
@matifali can you run `make fmt` by chance? i am continuing to see this error:

```
--- shfmt
.git/logs/refs/remotes/origin/cj/tools.go:1:1: expected 'package', found 0000000000000000000000000000000000000000
.git/logs/refs/remotes/origin/cj/tools.go:1:100: illegal character U+0040 '@'
.git/refs/remotes/origin/cj/tools.go:1:1: expected 'package', found 8964
```

2023-08-29 14:26 UTC, timquinlan requested changes, later dismissed
@ericpaulsen the only change I would recommend is adding more than one --platfors-filter value to the examples just to show the syntax of pulling multiple platforms, the thought being that most places will want windows and/or mac

2023-08-29 20:33 UTC, timquinlan approved these changes

2023-08-29 20:43 UTC, sempie commented on docs/ides/gateway.md
> +You will need to run a web server in order to serve requests to the backend and
I would just make sure to make it clear the files could be reachable by other means.  From the docs:
"productsInfoUrl: a path to products.json that was generated by the backend's downloader (it could be http://, https://, or **file://)** "

2023-08-29 20:55 UTC, ericpaulsen commented on docs/ides/gateway.md
> +You will need to run a web server in order to serve requests to the backend and
@sempie let me know if my most recent commit addresses this feedback.

2023-08-29 20:57 UTC, sempie commented on docs/ides/gateway.md
> +You will need to run a web server in order to serve requests to the backend and
looks good

2023-08-29 21:04 UTC, merged

2023-08-29 21:04 UTC, sempie approved these changes
Looks good