chore: idea: unify http responses further
coder/coder pull request #941
Opened 2022-04-08 21:48 UTC by f0ssel

> I'd like to open a question to the team: Would we like to have a unified response pattern like this PR implements? 
> 
> I've seen quite a few APIs, mostly from clouds, that do something similar. By doing this pattern, our clients can always expect the same format of response for success messages, errors, data, etc. I've always felt it was easier to work with as a consumer of the JSON API.

This was a discussion that led to just making `httpapi.Write()` useful for writing json data as well as the predefined response type.

2022-04-08 21:51 UTC, deansheather approved these changes

2022-04-08 23:05 UTC, kylecarbs requested changes
I _think_ `httpapi.Response` is our unified response pattern. Putting all message data inside a `data` field may promote sending a `message` or `error` along with a payload, which I'm not sure we have a use case for right now.

I'm not opposed to standardizing `render`, and I'd be fine with adding `httpapi.Write` with the third argument being an `interface{}` that we marshal for the caller.

By moving all data inside a `data` property, we wouldn't standardize the payload that our API consumers expect - we move the problem to the `data` field. API consumers can use the status code to check if the _data_ is truly what we say it is.

2022-04-09 00:48 UTC, kylecarbs approved these changes
This is a wise and nice improvement. Can we remove render from everywhere?

2022-04-11 13:18 UTC, johnstcn approved these changes
I like this.

2022-04-12 15:17 UTC, merged