feat: add envFrom value to Helm chart
coder/coder pull request #9587
Opened 2023-09-07 20:18 UTC by ericpaulsen

this PR adds support for the `coder.envFrom` value to the Helm chart. this will allow for Coder's environment variables to be passed from a single secret.

i'm pushing this in draft mode, because there is one caveat; the `$hasAccessURL` variable cannot identify if `CODER_ACCESS_URL` is set in the secret, so it will always default to the cluster-internal URL unless the access URL is specified using the traditional `coder.env` variable.

ideally, we parse the vars from the secret and pass them into the existing `containers.env` section in the template, but I have not gotten this to work. something akin to:

```tpl
{{ if .Values.coder.envFrom }}
{{- range $secretKey, $secretValue := .Values.coder.envFrom }}
# Handle the coder.envFrom case
{{- range $key, $value := dict $secretValue }}
- name: {{ $key }}
  value: {{ $value | b64dec | quote }}
{{- end }}
{{- end }}
{{- end }}
```

2023-09-08 03:10 UTC, deansheather reviewed
w.r.t the CODER_ACCESS_URL being automatically set, you could just put that behind a new value too like `coder.useClusterAccessURL` or something

2023-09-08 03:10 UTC, deansheather commented on helm/coder/values.yaml
> +  envFrom:
needs a comment in the same format as all other values

2023-09-08 03:10 UTC, deansheather commented on helm/coder/values.yaml
> +      name: ""
these need to be commented out before merge

2023-09-08 03:10 UTC, deansheather commented on helm/coder/templates/_coder.tpl
> +{{ toYaml . }}
Do you need an `nindent 2` here?

2023-09-14 06:22 UTC, spikecurtis requested changes, later dismissed
Please add a test that uses this with a new golden file

2023-09-14 06:22 UTC, spikecurtis commented on helm/coder/values.yaml
> +    tag: "v2.1.5"
This isn't supposed to be set in the repo

2023-09-14 06:22 UTC, spikecurtis commented on helm/coder/values.yaml
> +    pullSecrets:
why is this changed?

2023-09-14 06:36 UTC, deansheather reviewed
LGTM but I contributed so I won't approve

2023-09-19 12:03 UTC, spikecurtis approved these changes

2023-09-19 12:03 UTC, merged