docs: Prose Linting with Vale and Reviewdog
coder/coder pull request #9649
Opened 2023-09-12 19:58 UTC by stirby

Adding prose linter Vale with Github checks from Reviewdog. Plan to integrate stricter rules incrementally.

2023-09-14 21:01 UTC, stirby commented
I have read the CLA Document and I hereby sign the CLA

2023-09-14 21:01 UTC, stirby commented
recheck

2023-09-22 21:26 UTC, ammario requested changes

2023-09-22 21:26 UTC, ammario commented on .github/styles/Vocab/Cloud/accept.txt
> +(?i)Derp
DERP

2023-09-22 21:26 UTC, ammario commented on .github/styles/Google/vocab.txt
Why an empty file?

2023-09-22 21:26 UTC, ammario commented on .github/workflows/ci.yaml
> +          files: '["docs/about","docs/admin","docs/changelogs","docs/contributing","docs/ides","docs/images","docs/install","docs/networking","docs/platforms","docs/security","docs/templates","docs/d
You should generate the list of files using some future-proof method.

2023-09-22 21:26 UTC, ammario commented on docs/CONTRIBUTING.md
> +- `-n` or `--dry-run` will display the context without deployment. For example,
Let's keep latin for brevity.

2023-09-22 21:26 UTC, ammario commented on docs/CONTRIBUTING.md
> +retried by again, pressing "Run workflow," changing "Use workflow from" from
Punctuation should stay outside of quotations because we're typically referring to literal values as opposed to speech.

2023-09-22 21:26 UTC, ammario commented on docs/admin/auth.md
> +default, the value is set to "offline." This means that when a user
another example

2023-10-03 00:09 UTC, closed without merging

2023-10-04 12:57 UTC, bpmct commented
@stirby can we reopen this? I think we are just awaiting a review